### ISSUE TITLE
Notes about case weights

### ISSUE THREAD

**Issue by DavisVaughan** [tidymodels/planning#23]

**Comment by DavisVaughan** [comment]
yardstick `case_weights` draft https://github.com/tidymodels/yardstick/pull/233
workflows `add_case_weights()` https://github.com/tidymodels/workflows/pull/118
hardhat `bake_dependent_roles` https://github.com/tidymodels/hardhat/pull/166

**Comment by DavisVaughan** [comment]
yardstick:
- Walk through yardstick metrics and see which are easy / hard to do / require special attention
- `pr_curve()` and `roc_curve()` might need special attention
- Are there any metrics we can't do case weights with?

rsample:
- Only frequency weights (only integer)
- i.e. doing CV, (case weight value of 30, doing 10 fold, 3 of 30 go in assessment, 27 into analysis)
- End up with modified case weight column in both assessment and analysis (to maintain the original `30/N` proportion as closely as possible). Forced to be an integer in the modified column.
- Never allow case weights on time series functions

parsnip:
- Definitely start with `case_weights = ` as a vector

recipes:
- Preprocessing steps "need"? to know if the weights are importance VS frequency, because some steps don't make sense for importance
- TODO: Make a table of whether or not a step is done, and if it allows importance, frequency, both, or neither.
- TODO: Another table with per step information about whether or not weights are needed at `bake()` time (is this precise enough, @topepo to refine this)?
- Possibly don't allow case weights roles to be selected for recipe steps (can we make `recipes_eval_select()` error when this occurs? With an argument to opt out of this check?)
- `mutate(case_weights = as_case_weights())` ahead of time or `step_case_weights()` to basically do this for you
- If they do `update_role(x, new_role = "case_weights")`, throw an error if `x` isn't a case-weights vctr because we don't know what the type of the case weights are 
- Some check about not having >1 case weights column (formula method and in `update_role()`, unless `update_role()` also catches the formula method)

Thoughts:
Do we need a vctrs class based on a double/integer that knows what kinds of weighting is being done? frequency would be forced to integer. but how do we know what weighting scheme to "guess" that a vector is? i.e. if its integer do we assume "frequency"? might be best to never guess (zen of python). could live in hardhat so everyone can get it.


TODO:
- Davis on vctrs class
- Emil on recipes tables and logic behind `update_role()` (throw error if >1 weights column)
- Max on rsample scoping
- Max on yardstick table about easy/hard/unknown per metric
- Davis and Emil talk about weighted tables

**Comment by DavisVaughan** [comment]
2022-03-21

Davis:
- [x] Add weighted table to hardhat
- [ ] Finalize `add_case_weights()` PR in workflows
- [ ] Finalize `bake_dependent_roles` PR in hardhat
- [ ] Start looking into yardstick case weights support per metric

Emil:
- [x] Roles set for case weights when non-formula method used. 
- [x] Roles set for formula too. 
- [x] Check number of case weight columns
- [x] Check case weight is only role for case weight column
- [x] is_unsupervised_weights() function that FALSE for importance weights and TRUE for frequency weights.

**Comment by topepo** [comment]
Here is a summary of the yardstick changes (grouped by the type of change): 

The following metrics use a cross-tab to compute their statistics: `accuracy()`, `bal_accuracy()`, `detection_prevalence()`, `f_meas()`, `j_index()`, `kap()`, `mcc()`, `npv()`, `ppv()`, `precision()`, `recall()`, `sens()`, and `spec()`.

They should be trivial once we have the weighted table.

These functions are straight-forward since they need either a weighted mean or weighted correlation: `huber_loss_pseudo()`, `huber_loss()`, `mae()`, `mape()`, `mase()`, `mpe()`, `msd()`, `rmse()`, `rsq()`, and `smape().`

`ccc()`: needs weighted mean and variance; sum weights instead of using `n`.

`rpd()`: use weighted standard deviation and weighted RMSE

`classification_cost()`: `classification_cost_multiclass()` will need a weights arg that should be handled in the pivoting.

`iic()`: not completely sure. Prob use weighted mean and maybe weighted correlation.

`mn_log_loss()`: Changes to `mn_log_loss_multiclass()` alone to take weighted mean instead of sum.

`poisson_log_loss()`: take weighted mean of `dpois()` vector results.

`rsq_trad()`: use weighted sums. Examples in `summary.lm()`

`pr_auc()`, `pr_curve()`: use weighted precision and recall.

`roc_curve()`, `roc_auc()`, `roc_aunp()`, `roc_aunu()`: will need to go to cpp and use weighted precision and recall.

`gain_capture()`, `average_precision()`: use weighted table (not sure on some details though)

`rpiq()`: will need weighted RMSE and code for [weighted percentiles](https://en.wikipedia.org/wiki/Percentile#Weighted_percentile). There are some R functions that can compute them

**Comment by topepo** [comment]
For parsnip... 

We don't indicate whether a model can use case weights anywhere (suprise!). I thought that was in the encoding info. 

`fit.model_spec()` and `fit_xy()` get `case_weights` argument. The case weights vector will be saved to the `eval_env` environment. 

* Perhaps hardhat should have checks for case weights (multiples, right class etc)

`make_form_call()` and `make_xy_call()` get the model spec and eval environment. They do the substitutions into the call.  This will add the quoted weight vector to the call. 

Recall that some model functions don't use standardized argument names. For example, LiblineaR has a  `set_fit()`  specification of 

```
    protect = c("x", "y", "wi"),
    data = c(x = "data", y = "target"),
```

We will have to do the same with the case weights argument in some cases.

**Comment by topepo** [comment]
For parsnip, there are a bunch of models that can use weights but need their specifications updated: 

* multilevelmod: `lme4::lmer()`,  `nlme::gls()`, and `nlme::lme()`
* censored package models
* rules package
* treesnip package

xgboost can also use weights so we'll modify `parsnip::xgb_train()` to work. 

For baguette, those models can use weights but the main api (`bagger()`) doesn't have the options.

**Comment by topepo** [comment]
Also for parsnip, I'm working on a "grouped glm" function to use as an engine. This would be when you have grouped binomial data that already is formatted with integer case weights.

**Comment by topepo** [comment]
treesnip is still pending but the others [above](https://github.com/tidymodels/planning/issues/23#issuecomment-1079442126) are worked out. 

@EmilHvitfeldt is spark sorted?

**Comment by EmilHvitfeldt** [comment]
As far as I can tell, yes.

**Comment by topepo** [comment]
Started on unit tests (across all models): https://github.com/tidymodels/extratests/tree/case-weights-parsnip

I'll also end up putting integration tests that go from model to tuning here too.

**Comment by EmilHvitfeldt** [comment]
I'm going to close this issue as we are done with the big case weights push!
